#  <-- tasks file can include smaller files if warranted

# init
- name: set locale
  shell: localectl set-locale LANG=ja_JP.utf8
  when: ansible_env.LANG | default('') != 'ja_JP.utf8'
- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
- name: set proxy.sh
  template:
    force: yes
    src: proxy.sh
    dest: /etc/profile.d/proxy.sh
    owner: root
    group: root
    mode: 0644
  register: proxy_file
- name: source proxy.sh
  shell: source /etc/profile.d/proxy.sh
  when:
  - proxy_file is changed
- name: set yum proxy
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: "^proxy=.*$"
    insertafter: EOF
    line: "proxy={{ http_proxy }}"
- name: yum update
  yum:
    name: '*'
    state: latest
    skip_broken: yes

# CA
- name: set Local CA Certificate
  get_url:
    url: "{{ ca_url }}"
    dest: /etc/pki/ca-trust/source/anchors
    checksum: "sha256:{{ ca_sha256 }}"
    force: yes
  register: downloaded_ca
- name: extract ca
  shell: update-ca-trust extract
  when:
  - downloaded_ca is changed

# others
- name: disabled firewalld
  systemd:
    name: firewalld
    enabled: no
    daemon_reload: yes
  ignore_errors: yes
- name: disabled SELinux
  replace:
    path: /etc/selinux/config
    regexp: "^SELINUX=enforcing$"
    replace: "SELINUX=disabled"
- name: Password OK
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication no$"
    replace: "PasswordAuthentication yes"
  register: sshd_config
- name: restart sshd
  systemd:
    name: sshd
    state: restarted
    daemon_reload: yes
  when:
  - sshd_config is changed
